Fix Graylog log adapter not working after upgrading to Python 3.12
